# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""Generate compact 00-spec.md files for all stage-3 survivors."""
from pathlib import Path

OUT = Path("/Users/alejo/code/cliver/dev/pipeline/outputs/ideas")

# (slug, measure, name, summary, modes, attacker_stories, deps, flags, manual_review, failure_modes, record)
SPECS = [
# === m01 ===
("m01-ofac-sdn", "01", "OFAC SDN + Consolidated screen",
 "Screen the customer's legal name, DOB, and address against OFAC's Specially Designated Nationals list and the US Consolidated Sanctions list (which unions SDN with FSE, NS-PLC, SSI, etc.). Use the Treasury OFAC search API or a vendor wrapper. Fuzzy-match on name with score threshold; require human disposition on hits.",
 "D", "denied-individual, sanctioned-jurisdiction-routing",
 "OFAC sanctions list API; OpenSanctions; Treasury Consolidated Sanctions XML feed.",
 "ofac_sdn_hit; ofac_consolidated_hit",
 "Reviewer adjudicates fuzzy hits with secondary identifiers.",
 "Common name false positives.",
 "Match score + list snapshot date."),
("m01-global-sanctions-union", "01", "UN/EU/UK/CA/AU sanctions union",
 "Union of UN Security Council Consolidated List, EU Financial Sanctions File (FSF), UK OFSI Consolidated List, Canada SEMA, Australia DFAT — sourced via OpenSanctions or direct feeds. Single screening pipeline mirroring the OFAC pipeline. Required for non-US shipments.",
 "D", "denied-individual, sanctioned-jurisdiction-routing, foreign-buyer-shell",
 "OpenSanctions API; UN, EU, OFSI, DFAT, SEMA primary feeds.",
 "un_hit; eu_fsf_hit; uk_ofsi_hit; ca_sema_hit; au_dfat_hit",
 "Reviewer disposition on every hit.",
 "List freshness lag; transliteration variants.",
 "Match record + list snapshot."),
("m01-commercial-watchlist", "01", "Commercial watchlist (World-Check / Dow Jones / Bridger)",
 "Use a commercial PEP+sanctions+adverse-media aggregator (Refinitiv World-Check, Dow Jones Risk & Compliance, or LexisNexis Bridger) to catch entries before they appear on government lists and to surface adverse media.",
 "D", "denied-individual, gradual-legitimacy-accumulation",
 "World-Check API; Dow Jones Risk Center; Bridger Insight XG.",
 "watchlist_hit; pep_hit; adverse_media_hit",
 "Reviewer reviews adverse-media articles.",
 "License cost; false positives on PEP class.",
 "Vendor case ID + match record."),
("m01-delta-rescreen", "01", "Daily delta re-screening",
 "Re-screen every prior customer against newly added sanctions list entries each day; alert when an existing customer becomes a hit. Closes the gap when a customer is sanctioned after onboarding.",
 "D", "post-onboarding-sanction, gradual-legitimacy-accumulation",
 "OpenSanctions delta feed; internal customer DB.",
 "delta_new_hit",
 "Reviewer freezes account pending disposition.",
 "Identifier drift across re-screens.",
 "Delta diff + customer ID."),

# === m02 ===
("m02-ror-domain-match", "02", "ROR institutional domain match",
 "Resolve the customer's email domain against the ROR registry's `links` field for the claimed institution. Strict match on the apex domain (or a documented subdomain). Fast positive signal for legitimate academic affiliation.",
 "D, A", "free-mail-affiliation, lookalike-domain, dormant-domain",
 "ROR API.",
 "ror_domain_match; ror_domain_mismatch",
 "Reviewer adjudicates mismatches against directory.",
 "ROR coverage uneven outside US/EU; some institutions use multiple domains.",
 "ROR ID + matched domain."),
("m02-rdap-age", "02", "RDAP/WHOIS domain age + registrant",
 "Query RDAP for the customer's email domain to obtain registration date, registrant org, and last update. Flag domains <12 months old, recently transferred, or with privacy-redacted registrant on a claimed institutional domain.",
 "D, A", "dormant-domain, lookalike-domain, shell-company",
 "RDAP (free); fallback WHOIS.",
 "domain_age_lt_12mo; domain_recent_transfer; registrant_redacted",
 "Reviewer evaluates against claim.",
 "Privacy services hide registrant on legitimate small orgs.",
 "RDAP JSON snapshot."),
("m02-disposable-blocklist", "02", "Disposable / free-mail blocklist",
 "Match the email domain against curated lists of disposable mailbox providers (10minutemail, Mailinator, Guerrilla) and free-mail (gmail, yahoo, qq). Disposable = hard reject; free-mail on a claimed institutional order = soft flag.",
 "D, A", "free-mail-affiliation, disposable-mailbox",
 "disposable_email_blocklist (oss); fakefilter; Kickbox.",
 "disposable_domain; free_mail_with_institution_claim",
 "Reviewer escalates free-mail + institutional claim to m07 affiliation check.",
 "Lists lag new providers.",
 "List name + version."),
("m02-wayback", "02", "Wayback first-seen + content history",
 "Query the Internet Archive Wayback CDX API for the customer's email domain. Capture first-seen snapshot date and most-recent snapshot's content. Flag domains with no Wayback history, or whose Wayback history shows a content category change (parking page → research lab) within the past 12 months.",
 "A", "dormant-domain, drop-catch, lookalike-domain",
 "Wayback CDX API.",
 "no_wayback_history; recent_content_pivot",
 "Reviewer compares snapshots.",
 "Small legitimate sites lack history.",
 "First-seen date + sampled snapshot URLs."),
("m02-mx-tenant", "02", "MX / M365 / Workspace tenant + SPF/DMARC",
 "Resolve MX records for the email domain; identify hosting (Google Workspace, M365, self-hosted, generic provider). Fetch SPF and DMARC records. Flag self-hosted or generic providers on claimed institutional domains; flag missing DMARC.",
 "D, A", "lookalike-domain, inbox-compromise, shell-company",
 "DNS resolver; M365 tenant lookup endpoint; Workspace MX patterns.",
 "mx_generic_provider; spf_missing; dmarc_missing; tenant_mismatch",
 "Reviewer correlates with claim.",
 "Some legitimate institutions self-host.",
 "MX/SPF/DMARC records."),
("m02-inbox-roundtrip", "02", "Inbox round-trip verification",
 "Send a signed token to the email address; require the user to click through within a short window. Confirms control of the inbox and creates a record of the verification.",
 "D", "lookalike-domain, dormant-domain, free-mail-affiliation",
 "Internal mailer; signed-token library.",
 "roundtrip_failed; roundtrip_expired",
 "Reviewer reissues if expired.",
 "Inbox forwarding hides true recipient.",
 "Token issuance + click timestamps."),
("m02-dangling-dns", "02", "Dangling-DNS / drop-catch detector",
 "Detect domains whose DNS points to abandoned cloud resources (S3, Heroku) or that were recently drop-caught. Cross-reference Tranco rank delta and CT first-seen to spot domains repurposed from prior owners.",
 "A", "drop-catch, dormant-domain, dangling-dns",
 "Tranco list; crt.sh; cloud-takeover oss tooling.",
 "dangling_dns_target; drop_catch_recent",
 "Reviewer correlates with WHOIS history.",
 "False positives on legitimate cloud migrations.",
 "DNS + CT snapshots."),

# === m03 ===
("m03-usps-rdi-cmra", "03", "USPS RDI + CMRA flag",
 "Submit shipping address to USPS Address Information API (or licensed reseller) and capture the Residential Delivery Indicator (RDI) and CMRA (Commercial Mail Receiving Agent) flag. CMRA = PO-box-equivalent for KYC purposes.",
 "D", "po-box-shipping, cmra-shipping",
 "USPS Web Tools / licensed CASS reseller.",
 "address_is_cmra; address_is_po_box",
 "Reviewer escalates CMRA.",
 "International addresses unsupported.",
 "USPS DPV + CMRA flags."),
("m03-smarty-melissa", "03", "Smarty / Melissa address verification",
 "Use Smarty (formerly SmartyStreets) or Melissa Global Address Verification for international PO box, packaging-store, and CMRA detection where USPS is unavailable. Returns DPV match, CMRA, and address-type code.",
 "D", "po-box-shipping, cmra-shipping, foreign-buyer-shell",
 "Smarty US+International API; Melissa Global Address API.",
 "smarty_cmra; smarty_po_box; melissa_cmra",
 "Reviewer adjudicates ambiguous DPV codes.",
 "Vendor coverage gaps in some countries.",
 "Vendor response JSON."),
("m03-pobox-regex-sop", "03", "PO Box / APO regex + reviewer SOP",
 "Deterministic regex over the address string for `PO Box`, `P.O. Box`, `Postfach`, `Casilla`, `Apartado`, plus APO/FPO/DPO patterns. Catches misformatted entries that bypass DPV.",
 "D", "po-box-shipping, apo-fpo-shipping",
 "Internal regex library.",
 "regex_po_box; regex_apo_fpo",
 "Reviewer reviews any regex hit.",
 "Locale-specific phrasing variants.",
 "Matched regex + raw string."),

# === m04 ===
("m04-usps-rdi", "04", "USPS RDI residential indicator",
 "USPS Residential Delivery Indicator distinguishes residential vs business addresses with high US accuracy. Reuses the m03 USPS call.",
 "D", "residential-shipping, home-receiver-fronting",
 "USPS Web Tools.",
 "address_is_residential",
 "Reviewer adjudicates residential addresses for institutional orders.",
 "US-only.",
 "RDI flag."),
("m04-google-places-business", "04", "Google Places business presence",
 "Query Google Places API at the address coordinates for a registered business. Inspect business category, photos, and reviews. Lack of any Places business at the lat/lng on a claimed institutional address is a soft flag.",
 "D, A", "residential-shipping, address-spoofing, ghost-office",
 "Google Places API.",
 "no_places_business_at_address; places_category_mismatch",
 "Reviewer reviews mismatched categories.",
 "New labs may not be on Places.",
 "Places query response."),
("m04-county-assessor", "04", "County assessor parcel use-code (US)",
 "Look up the parcel at the address against the county assessor's open data (or via Regrid / ATTOM aggregator). Use code (residential / commercial / institutional / mixed-use) is authoritative ground truth.",
 "D", "residential-shipping, ghost-office",
 "Regrid; ATTOM Data; county open-data portals.",
 "parcel_use_residential; parcel_use_mixed",
 "Reviewer correlates with claim.",
 "Coverage uneven across counties.",
 "Parcel record."),
("m04-str-coloc-sop", "04", "STR / Wayback co-location SOP",
 "Reviewer SOP: when an address is flagged residential or ambiguous, search Airbnb / VRBO listings and Wayback for the address. STR co-location = hard flag (short-term-rental drop).",
 "A", "short-term-rental-drop, ghost-office",
 "Manual; Airbnb search; Wayback.",
 "address_is_str; address_wayback_str_history",
 "Reviewer documents co-location finding.",
 "Manual; not bulk.",
 "Search results."),

# === m05 ===
("m05-ror-gleif-canonical", "05", "ROR/GLEIF/Companies House canonical address cross-ref",
 "For a claimed institution, fetch its canonical address(es) from ROR, GLEIF (LEI record), and Companies House. Compare to the customer-provided shipping/billing address with normalized geocoding. Mismatch beyond a tolerance is a flag.",
 "D, A", "ghost-office, address-spoofing, shell-company",
 "ROR API; GLEIF API; Companies House API.",
 "canonical_address_mismatch; institution_no_canonical_record",
 "Reviewer evaluates legitimate satellite sites.",
 "Multi-campus institutions; ROR doesn't capture every site.",
 "Canonical address + match score."),
("m05-google-places-campus", "05", "Google Places + OSM campus polygon",
 "Resolve the institution's name to a Google Places entry and OSM relation; verify the customer address falls within the campus polygon (or known affiliate building). Strong positive signal.",
 "D", "ghost-office, address-spoofing",
 "Google Places API; OpenStreetMap Nominatim + Overpass.",
 "address_inside_campus_polygon; address_outside_campus_polygon",
 "Reviewer adjudicates affiliate buildings.",
 "Polygons missing for many institutions.",
 "Polygon ID + containment result."),
("m05-incubator-tenant", "05", "Incubator / coworking tenant directory",
 "If the address resolves to a known biotech incubator (LabCentral, JLABS, BioLabs, IndieBio, etc.), require that the customer's organization appear in the incubator's public tenant directory.",
 "A", "incubator-fronting, ghost-office",
 "Incubator tenant pages (LabCentral, JLABS, etc.).",
 "incubator_address_no_tenant_listing",
 "Reviewer contacts incubator manager.",
 "Tenant lists lag move-ins.",
 "Tenant page snapshot."),
("m05-two-contact-sop", "05", "Two-contact directory verification SOP",
 "Reviewer SOP: contact the institution via two channels (main switchboard + departmental email from the public directory) to confirm the customer's affiliation and shipping authorization. Used for borderline cases.",
 "A", "shell-company, cro-framing, ghost-office",
 "Manual.",
 "two_contact_unconfirmed",
 "Reviewer logs both contacts and outcomes.",
 "Time-intensive; not scalable.",
 "Call/email log."),

# === m06 ===
("m06-bis-country-groups", "06", "BIS Country Group D/E + EAR licensing matrix",
 "Map the destination country to BIS Country Groups (A:5/A:6 allies, D:1/D:5 concerns, E:1/E:2 embargoed). Apply EAR licensing requirements per ECCN; block Group E without exception, escalate Group D for license review.",
 "D", "sanctioned-jurisdiction-routing, transshipment, foreign-buyer-shell",
 "BIS EAR Country Chart; internal ECCN matrix.",
 "country_group_e; country_group_d_license_required",
 "Reviewer applies licensing decision.",
 "License determinations are item-specific.",
 "Country group + ECCN."),
("m06-iso-country-normalize", "06", "ISO 3166 normalization + sanctioned-territory geofence",
 "Normalize country names / ISO codes (handle Crimea, Donetsk, Luhansk, North Korea variants). Geofence sanctioned sub-regions inside otherwise allowed countries.",
 "D", "sanctioned-jurisdiction-routing, transshipment",
 "ISO 3166-2; OFAC sectoral sanctions territory list.",
 "sanctioned_subregion",
 "Reviewer reviews subregion hits.",
 "Region naming variants.",
 "Normalized country/region."),
("m06-bis-entity-list", "06", "BIS Entity List + DPL consignee screen",
 "Screen the consignee org and end-user against the BIS Entity List, Denied Persons List, Unverified List, and Military End-User list. Hard block on Entity / DPL hits.",
 "D", "denied-end-user, transshipment",
 "BIS Consolidated Screening List API.",
 "bis_entity_list_hit; dpl_hit; mil_end_user_hit",
 "Reviewer disposition on hits.",
 "Name fuzzing.",
 "Match record."),
("m06-freight-forwarder-denylist", "06", "Freight forwarder / customs broker denylist",
 "Maintain an internal denylist of freight forwarders and customs brokers known for transshipment to embargoed destinations. Cross-reference the shipping address and end-recipient.",
 "A", "transshipment, freight-forwarder-laundering",
 "Industry advisories; OFAC enforcement actions; internal history.",
 "freight_forwarder_denylist_hit",
 "Reviewer escalates to export compliance.",
 "List curation lag.",
 "Denylist version + match."),
("m06-hs-eccn-classification", "06", "HS code / ECCN classification SOP",
 "Reviewer SOP for assigning HS code and ECCN to the synthesis order based on length, modification, and host. Drives licensing requirements per m06-bis-country-groups.",
 "D", "transshipment, sanctioned-jurisdiction-routing",
 "BIS CCL; HS schedule.",
 "eccn_license_required",
 "Reviewer applies classification.",
 "Classification ambiguity for novel items.",
 "ECCN + HS assignment."),

# === m07 ===
("m07-incommon-edugain", "07", "InCommon + eduGAIN federation IdP enumeration",
 "Verify the customer's email domain corresponds to a federation-registered IdP in InCommon (US) or eduGAIN (international). IdP membership is strong evidence of an academic-grade affiliation.",
 "D, A", "free-mail-affiliation, shell-company, lookalike-domain",
 "InCommon metadata; eduGAIN federation metadata.",
 "domain_in_incommon; domain_in_edugain; domain_no_federation",
 "Reviewer adjudicates non-federation institutions.",
 "Many small / corporate research orgs not in federations.",
 "Federation entry."),
("m07-directory-scrape", "07", "Institutional directory people-search scrape",
 "Scrape (or query) the institution's people-search directory for the customer's name. Verify name, email, role, department.",
 "A", "it-persona-manufacturing, visiting-researcher, gradual-legitimacy-accumulation",
 "Institution-specific scrape; cached HTML.",
 "directory_no_match; directory_role_mismatch",
 "Reviewer manually verifies near-misses.",
 "Directory privacy filters; lag for new hires.",
 "Directory snippet."),
("m07-proxycurl-linkedin", "07", "Proxycurl LinkedIn person-lookup",
 "Use Proxycurl Person Lookup to fetch the customer's LinkedIn profile by name + company domain. Compare current employer, employment tenure, profile age.",
 "A", "gradual-legitimacy-accumulation, shell-company, it-persona-manufacturing",
 "Proxycurl API.",
 "linkedin_no_profile; linkedin_employer_mismatch; linkedin_profile_lt_12mo",
 "Reviewer adjudicates near-matches.",
 "LinkedIn ToS uncertainty; common names.",
 "Proxycurl JSON."),
("m07-google-site-search", "07", "site:domain name search",
 "Query Google CSE / Bing for `site:<institution-domain> \"<customer name>\"`. Hits on faculty pages, lab pages, publications, news constitute corroboration.",
 "A", "it-persona-manufacturing, visiting-researcher",
 "Google CSE; Bing Web Search API.",
 "no_site_search_hits",
 "Reviewer evaluates hit quality.",
 "False negatives for new researchers.",
 "Search query + result URLs."),
("m07-visiting-scholar-sop", "07", "Visiting-scholar new-hire corroboration SOP",
 "When the customer claims visiting-scholar / postdoc / new-hire status, require at least one positive corroborator from institution news, dept events, or sponsoring-PI confirmation email.",
 "A", "visiting-researcher, it-persona-manufacturing",
 "Bing News API; manual sponsor email.",
 "new_hire_zero_corroborators",
 "Reviewer requests sponsoring PI confirmation.",
 "Most legit new-hires get no press.",
 "Corroborator URLs / email log."),

# === m08 ===
("m08-bis-entity-csl", "08", "BIS Entity List + Consolidated Screening List",
 "Screen the customer's institution against the US Consolidated Screening List (BIS Entity, DPL, UVL, MEU; State DDTC; Treasury OFAC). Hard block on hits.",
 "D", "sanctioned-institution, denied-end-user",
 "Trade.gov CSL API.",
 "csl_entity_hit",
 "Reviewer disposition.",
 "Name fuzzing.",
 "Match record."),
("m08-commercial-pep-watchlist", "08", "Commercial PEP/entity watchlist",
 "Use World-Check / Dow Jones / Sayari / Bridger entity screening to catch entities flagged for adverse media or PEP exposure before government listing.",
 "A", "sanctioned-institution, beneficial-owner-laundering",
 "World-Check; Dow Jones RC; Sayari Graph; Bridger XG.",
 "commercial_entity_hit",
 "Reviewer reviews adverse-media articles.",
 "License cost.",
 "Vendor case ID."),
("m08-internal-denylist", "08", "Internal institution denylist",
 "Maintain an internal denylist of previously declined or sanctioned-after-onboarding institutions. Hard block on match.",
 "D, A", "previously-declined, beneficial-owner-laundering, cro-identity-rotation",
 "Internal database.",
 "internal_denylist_hit",
 "Reviewer adjudicates name collisions.",
 "Identifier drift.",
 "Internal record ID."),

# === m09 ===
("m09-corp-registry-stack", "09", "Companies House / EDGAR / OpenCorporates / foreign registry",
 "Verify the institution's legal existence and life-sciences scope of activity via the appropriate national corporate registry. Capture incorporation date, status (active/dissolved), registered office, officers, SIC/NAICS code.",
 "D, A", "shell-company, dissolved-company, beneficial-owner-laundering",
 "Companies House API; SEC EDGAR; OpenCorporates; foreign registries.",
 "registry_no_record; registry_dissolved; sic_not_life_sciences; registry_recent_incorp",
 "Reviewer reviews mismatched SIC.",
 "Registry coverage gaps; SIC misclassification.",
 "Registry record snapshot."),
("m09-pubmed-affiliation", "09", "PubMed + bioRxiv affiliation history",
 "Search PubMed and bioRxiv for publications affiliated with the institution name in the past 5 years. Counts as positive evidence of real life-sciences activity.",
 "A", "shell-nonprofit, paper-shell-research-org",
 "NCBI E-utilities; bioRxiv API.",
 "no_pubmed_affiliation_5yr",
 "Reviewer adjudicates name variants.",
 "Brand-new institutions lack history.",
 "Publication count + sample DOIs."),
("m09-clinicaltrials-fda", "09", "ClinicalTrials.gov + FDA establishment registration",
 "Cross-check the institution against ClinicalTrials.gov sponsors/sites and the FDA establishment registration database (drug, device, blood, tissue). Either presence is positive evidence.",
 "A", "shell-nonprofit, paper-shell-research-org",
 "ClinicalTrials.gov API; FDA Establishment Registration DB.",
 "no_ctgov_no_fda_registration",
 "Reviewer adjudicates non-clinical labs.",
 "Many legitimate basic-research labs are absent.",
 "ID match."),
("m09-registered-agent-denylist", "09", "Mass-registered-agent / virtual-office denylist",
 "Maintain a denylist of mass-formation registered agents (Northwest, Incfile, ZenBusiness) and virtual-office providers (Regus, Davinci, Alliance) at the institution's registered address. Combined with other shell signals.",
 "A", "shell-company, virtual-office-fronting",
 "Internal denylist; OpenCorporates agent counts.",
 "registered_agent_mass_formation; address_virtual_office",
 "Reviewer combines with other signals.",
 "Mass agents legitimately serve thousands.",
 "Agent name + count."),
("m09-irs-990", "09", "IRS Form 990 + Candid nonprofit financials",
 "For US 501(c)(3) institutions, fetch the most recent Form 990 from IRS or Candid (formerly GuideStar). Inspect revenue, program expenses, board, and program description for life-sciences alignment.",
 "A", "shell-nonprofit",
 "IRS 990 dataset; Candid API; ProPublica Nonprofit Explorer.",
 "no_990; 990_revenue_implausible; 990_program_not_life_sciences",
 "Reviewer reads program description.",
 "Smallest nonprofits file 990-N postcards.",
 "990 record."),
("m09-domain-auth-stack", "09", "MX/SPF/DMARC + WHOIS-history life-sciences signal",
 "For the institution's claimed primary domain, inspect MX/SPF/DMARC alignment and WHOIS history (registration date, transfer events). Used as a corroborating signal alongside the registry stack.",
 "A", "shell-company, dormant-domain",
 "DNS; RDAP; DomainTools history (optional).",
 "domain_recent; domain_no_mail_auth",
 "Reviewer correlates with registry record.",
 "False positives on small legitimate orgs.",
 "DNS/RDAP snapshot."),

# === m10 ===
("m10-binlist-stack", "10", "BIN classification stack (binlist + BinDB + Neutrino)",
 "Classify the BIN of the customer's payment card via binlist.net, BinDB, and NeutrinoAPI. Identify card brand, issuer, country, and `prepaid` / `gift` flag.",
 "D", "prepaid-gift-card, anonymous-funding",
 "binlist.net; BinDB; NeutrinoAPI BIN Lookup.",
 "bin_prepaid; bin_gift; bin_unknown",
 "Reviewer adjudicates unknown BINs.",
 "BIN tables lag new issuances.",
 "BIN lookup record."),
("m10-stripe-funding", "10", "Stripe / Adyen funding-source",
 "Use Stripe `payment_method.card.funding` (or Adyen equivalent) to obtain the issuer-reported funding type (`credit`, `debit`, `prepaid`, `unknown`). Authoritative because the PSP queries the network directly.",
 "D", "prepaid-gift-card, anonymous-funding",
 "Stripe API; Adyen API.",
 "psp_funding_prepaid; psp_funding_unknown",
 "Reviewer escalates `unknown`.",
 "Issuers occasionally misreport.",
 "PSP funding string."),
("m10-prepaid-issuer-denylist", "10", "Prepaid issuer / virtual single-use BIN denylist",
 "Maintain a denylist of prepaid-card issuers (Netspend, Green Dot, Bancorp, Sutton) and virtual single-use BIN providers (Privacy.com, Revolut Disposable). Hard block.",
 "A", "prepaid-gift-card, virtual-single-use-bin",
 "Internal denylist; PSP hard-block rules.",
 "prepaid_issuer_denylist_hit; virtual_bin_provider_hit",
 "Reviewer adjudicates legitimate corporate prepaid.",
 "List curation lag.",
 "Issuer name + BIN."),

# === m11 ===
("m11-psp-config-audit", "11", "PSP config audit (no crypto methods)",
 "Periodic audit that the live Stripe/Adyen/Braintree configuration does not have any crypto-related payment methods enabled (Coinbase, Bitpay, etc.). Code-as-config check in CI.",
 "D", "crypto-funding",
 "PSP admin APIs.",
 "crypto_method_enabled",
 "Reviewer reverts config drift.",
 "New PSP methods can appear without notice.",
 "Config snapshot."),
("m11-crypto-onramp-denylist", "11", "Crypto-debit BIN + on-ramp referrer denylist",
 "Block payment cards issued by known crypto-debit programs (Coinbase Card, Crypto.com Visa, BlockFi, Wirex) via BIN denylist. Block HTTP referrers from known on-ramps.",
 "A", "crypto-funding, crypto-debit-card",
 "Internal BIN denylist; HTTP referrer rules.",
 "crypto_debit_bin_hit; crypto_onramp_referrer",
 "Reviewer adjudicates marginal cases.",
 "List lag.",
 "BIN + referrer."),
("m11-msa-prohibition", "11", "MSA prohibition + order-text scan",
 "Master Services Agreement explicitly prohibits crypto funding; periodic scan of order-text fields for crypto wallet addresses or coin tickers.",
 "A", "crypto-funding",
 "Internal regex over order metadata.",
 "order_text_crypto_reference",
 "Reviewer reviews textual hits.",
 "Legitimate research mentions of crypto.",
 "Matched text."),

# === m12 ===
("m12-psp-avs", "12", "PSP AVS + Plaid Identity",
 "Use PSP AVS (Stripe / Adyen / Braintree) to confirm billing address matches issuer record. Plaid Identity adds bank-account name verification.",
 "D", "billing-shipping-mismatch, stolen-card, third-party-billing",
 "Stripe / Adyen / Braintree AVS; Plaid Identity API.",
 "avs_no_match; plaid_name_mismatch",
 "Reviewer reviews AVS partial matches.",
 "International AVS coverage uneven.",
 "AVS code + Plaid response."),
("m12-procurement-network", "12", "PaymentWorks / Jaggaer / SAM.gov supplier registration",
 "If the customer is a US institution, verify supplier registration in PaymentWorks, Jaggaer, or SAM.gov. Confirms the institution's procurement office authorized the payment relationship.",
 "A", "third-party-billing, shell-company",
 "PaymentWorks; Jaggaer; SAM.gov.",
 "no_supplier_registration",
 "Reviewer contacts procurement office.",
 "Coverage limited to enrolled institutions.",
 "Registration ID."),
("m12-pcard-bin", "12", "P-Card / institutional BIN allowlist",
 "Recognize institutional purchasing-card BIN ranges from major issuers (US Bank PaymentNet, JPM, Citi). P-Card on a claimed institutional order is positive corroboration.",
 "D", "personal-card-on-institutional-order",
 "Issuer BIN documentation.",
 "p_card_bin_match",
 "Reviewer treats as positive signal.",
 "Some P-Cards are unbranded.",
 "BIN + issuer."),
("m12-billing-shipping-consistency", "12", "Billing↔shipping↔institution consistency",
 "Deterministic rule: billing address, shipping address, and institutional canonical address (m05) must form a consistent set within a tolerance, OR the customer must explain divergence.",
 "D", "billing-shipping-mismatch, third-party-billing",
 "Internal rules engine.",
 "billing_shipping_inconsistent",
 "Reviewer reviews divergences.",
 "Distributed institutions; legitimate forwarders.",
 "Triple comparison record."),
("m12-fintech-denylist", "12", "Mercury / Brex / Wise consumer-fintech denylist",
 "When the billing instrument is from a consumer-fintech / neobank (Mercury, Brex, Wise, Revolut Business) on a claimed institutional order, soft flag — neobanks are common shell-company funding rails.",
 "A", "shell-company, third-party-billing",
 "Internal BIN/IBAN denylist.",
 "fintech_neobank_billing",
 "Reviewer requests procurement-office confirmation.",
 "Some legitimate small institutions use Brex.",
 "Issuer + BIN."),

# === m13 ===
("m13-twilio-lookup", "13", "Twilio Lookup line-type intelligence",
 "Twilio Lookup v2 returns line type (`mobile`, `landline`, `voip`, `tollFree`, `nonFixedVoip`), carrier, and country. `voip` and `nonFixedVoip` on a claimed institutional contact = soft flag.",
 "D", "voip-disposable-phone, burner-phone",
 "Twilio Lookup v2 API.",
 "phone_voip; phone_nonfixed_voip",
 "Reviewer adjudicates with secondary contact.",
 "Some legitimate institutions use VoIP PBX.",
 "Lookup response."),
("m13-telesign-phoneid", "13", "Telesign PhoneID + risk score",
 "Telesign PhoneID returns line type, carrier, risk score, and recent SIM-swap activity. Used as a second source.",
 "D, A", "voip-disposable-phone, sim-swap, burner-phone",
 "Telesign PhoneID API.",
 "telesign_high_risk; telesign_recent_sim_swap",
 "Reviewer adjudicates risk score.",
 "Score opacity.",
 "Telesign response."),
("m13-callback-sop", "13", "Callback to institutional switchboard SOP",
 "Reviewer SOP: for escalated cases, place an outbound call to the institution's main switchboard (looked up independently from the customer-supplied number) and ask to be transferred to the customer.",
 "A", "voip-disposable-phone, it-persona-manufacturing",
 "Manual.",
 "callback_failed",
 "Reviewer documents call.",
 "Time-intensive.",
 "Call log."),
("m13-rebind-cadence", "13", "Phone re-verification cadence + SIM-swap",
 "Re-verify the customer's phone every N months and on every high-risk event; couple with SIM-swap lookup (Telesign / Prove) to detect account takeover via phone.",
 "D", "sim-swap, account-takeover",
 "Telesign; Prove.",
 "rebind_failed; sim_swap_recent",
 "Reviewer freezes account on swap.",
 "Cadence tuning.",
 "Re-verification log."),

# === m14 ===
("m14-jumio", "14", "Jumio document + selfie liveness",
 "Jumio Identity Verification: ID document capture (3000+ documents, 200+ countries), NFC where supported, active+passive liveness, biometric match. Returns IAL2-equivalent assurance.",
 "D", "synthetic-identity, document-fraud, deepfake-selfie",
 "Jumio API.",
 "jumio_doc_failed; jumio_liveness_failed; jumio_face_no_match",
 "Reviewer reviews failed cases.",
 "Document coverage gaps.",
 "Jumio reference + decision."),
("m14-onfido", "14", "Onfido document + biometric",
 "Onfido Studio workflow: document classification, authenticity, face match, liveness. Alternative IAL2 vendor with stronger UK/EU coverage.",
 "D", "synthetic-identity, document-fraud, deepfake-selfie",
 "Onfido API.",
 "onfido_doc_failed; onfido_face_no_match",
 "Reviewer reviews failed cases.",
 "Vendor lock-in.",
 "Onfido reference."),
("m14-persona", "14", "Persona inquiry workflow",
 "Persona configurable inquiry: document, selfie, database, government ID checks. Strong workflow customization for tiered IAL2/IAL3.",
 "D", "synthetic-identity, document-fraud",
 "Persona API.",
 "persona_inquiry_failed",
 "Reviewer reviews flagged inquiries.",
 "Configuration drift.",
 "Persona inquiry ID."),
("m14-stripe-identity", "14", "Stripe Identity (low-friction)",
 "Stripe Identity for lower-risk tiers; integrated with PSP, lower friction but lower assurance than Jumio/Onfido.",
 "D", "document-fraud",
 "Stripe Identity API.",
 "stripe_identity_failed",
 "Reviewer escalates failures to Jumio.",
 "Lower assurance.",
 "Stripe verification ID."),
("m14-login-gov-id-me", "14", "Login.gov / ID.me / GOV.UK One Login federated IAL2",
 "Federated IAL2 via Login.gov, ID.me, or GOV.UK One Login. Government-operated IDV; eliminates vendor risk for US-government-credentialed users.",
 "D", "synthetic-identity",
 "Login.gov OIDC; ID.me OIDC; GOV.UK One Login OIDC.",
 "login_gov_failed; id_me_failed",
 "Reviewer adjudicates failed federated logins.",
 "Limited to enrolled users.",
 "Federation assertion."),
("m14-nfc-epassport", "14", "NFC ePassport chip read (ICAO PKD)",
 "Read the ICAO 9303 ePassport chip via mobile NFC; verify document signing certificate against the ICAO PKD. Highest-assurance document check.",
 "D", "document-fraud, synthetic-identity",
 "Vendor SDK (Jumio / Onfido / Veriff support); ICAO PKD.",
 "nfc_chip_failed; pkd_cert_invalid",
 "Reviewer reviews failures.",
 "Requires NFC-capable device.",
 "Chip read result."),
("m14-fido2-stepup", "14", "FIDO2 / WebAuthn order-time step-up + device binding",
 "At order time, require a FIDO2/WebAuthn assertion bound to a device registered during onboarding. Re-binds the human to the order. Combines with `max_age=0` SOP from m16.",
 "D, A", "account-takeover, session-hijack, dormant-account",
 "WebAuthn library; FIDO2 hardware tokens.",
 "webauthn_failed; device_unbound",
 "Reviewer re-enrolls device on legitimate failures.",
 "Token loss.",
 "Assertion record."),
("m14-cross-tenant-biometric-dedup", "14", "Cross-tenant biometric dedup",
 "In-house + vendor face-template dedup across all customers; flag when one biometric template is bound to multiple distinct identities (synthetic-identity factory) or when one identity has multiple templates.",
 "A", "synthetic-identity, identity-rotation",
 "In-house face embeddings; vendor cross-tenant dedup.",
 "biometric_template_collision",
 "Reviewer investigates collisions.",
 "Privacy / consent constraints.",
 "Template ID + collision count."),

# === m15 ===
("m15-structured-form", "15", "Structured SOC declaration form",
 "Replace free-text SOC fields with a structured form (intended use category, host organism, target gene, BSL level, IBC approval status). Each field has a controlled vocabulary.",
 "D", "soc-misdeclaration, soc-omission",
 "Internal form.",
 "field_missing; field_unsupported_value",
 "Reviewer reviews submissions.",
 "Vocabulary completeness.",
 "Form submission record."),
("m15-llm-extraction", "15", "LLM extraction + deterministic cross-ref",
 "Use an LLM to extract structured SOC fields from any free-text the customer provides; deterministically cross-reference against the structured form (m15-structured-form) and the order's sequence content.",
 "D, A", "soc-misdeclaration, soc-omission",
 "Anthropic Claude / OpenAI; deterministic comparator.",
 "llm_extraction_disagreement; llm_form_mismatch",
 "Reviewer adjudicates disagreements.",
 "LLM hallucination on edge cases.",
 "LLM output + diff."),
("m15-screening-reconciliation", "15", "Screening reconciliation (Aclid/Battelle/SecureDNA)",
 "Daily reconciliation of SOC declarations against sequence-screening results from Aclid, Battelle UltraScreen, and SecureDNA. Disagreement (e.g., declared `vaccine adjuvant`, screened as `select agent`) triggers escalation.",
 "D, A", "soc-misdeclaration, sequence-of-concern",
 "Aclid; Battelle UltraScreen; SecureDNA.",
 "soc_screening_disagreement",
 "Reviewer escalates to scientific review.",
 "Vendor coverage differs.",
 "Reconciliation diff."),
("m15-ibc-attestation", "15", "IBC / sponsor PI attestation",
 "Require an Institutional Biosafety Committee (IBC) approval document or sponsor-PI attestation upload for SOC orders. Verify against m17 IBC roster.",
 "D, A", "soc-misdeclaration, no-ibc-approval",
 "Manual upload; m17 roster cross-check.",
 "ibc_doc_missing; ibc_doc_unverified",
 "Reviewer verifies signatures.",
 "Forged docs.",
 "Document hash."),
("m15-drift-detector", "15", "Cross-order SOC drift detector",
 "Detect when a customer's SOC declarations change pattern across orders (escalating concern, switching organisms, narrowing toward a known threat). Statistical drift detector.",
 "A", "soc-drift, gradual-escalation",
 "Internal time-series.",
 "soc_drift_detected",
 "Reviewer reviews drift episodes.",
 "Legitimate research pivots.",
 "Drift timeline."),

# === m16 ===
("m16-auth0-okta", "16", "Auth0 / Okta / Cognito hosted MFA",
 "Use a hosted IdP (Auth0, Okta, AWS Cognito) for MFA enrollment, enforcement, and adaptive risk. Centralizes MFA policy.",
 "D", "account-takeover, credential-stuffing",
 "Auth0 / Okta / Cognito.",
 "mfa_not_enrolled; mfa_failed",
 "Reviewer adjudicates lockouts.",
 "Vendor lock-in.",
 "IdP audit log."),
("m16-webauthn-yubikey", "16", "WebAuthn / YubiKey hardware token enforcement",
 "Require WebAuthn (FIDO2) hardware tokens for SOC-tier customers. Phishing-resistant; eliminates SMS bypass.",
 "D", "phishing, sms-bypass, account-takeover",
 "WebAuthn library; YubiKey hardware.",
 "no_webauthn_enrolled",
 "Reviewer issues replacement tokens.",
 "Token cost / loss.",
 "Authenticator metadata."),
("m16-no-sms-no-email-reset", "16", "No-SMS, no-email-reset SOP",
 "Policy: SMS disallowed as second factor; password reset never via email-only. Resets require IDV re-bind.",
 "D", "sim-swap, email-takeover, sms-bypass",
 "Internal policy + IdP config.",
 "policy_sms_used; reset_email_only_used",
 "Reviewer audits exceptions.",
 "User friction.",
 "Policy audit."),
("m16-spycloud-breach", "16", "SpyCloud / Constella breach-credential check",
 "Check the customer's email + password against SpyCloud / Constella breach datasets. Force reset on hit. Combines with HIBP Passwords for k-anonymity password check.",
 "A", "credential-stuffing, account-takeover",
 "SpyCloud API; Constella API; HIBP Passwords.",
 "breach_credential_hit",
 "Reviewer forces reset.",
 "Privacy implications.",
 "Breach record."),
("m16-dormancy-reidv", "16", "Dormancy re-IDV trigger",
 "If an account is dormant > 6 months, force re-IAL2 (m14) and re-bind on next login. Closes dormant-account-takeover.",
 "A", "dormant-account-takeover",
 "Internal dormancy timer; m14 vendor.",
 "dormancy_reidv_required",
 "Reviewer adjudicates legitimate returns.",
 "User friction.",
 "Dormancy log."),
("m16-order-time-stepup", "16", "Order-time max_age=0 step-up",
 "At order submission, require a fresh authentication (`max_age=0`) — re-prompt for MFA. SOP that ties order to a fresh auth event.",
 "D, A", "session-hijack, account-takeover",
 "OIDC max_age parameter.",
 "stepup_failed",
 "Reviewer adjudicates failed step-ups.",
 "Friction at order time.",
 "Auth event timestamp."),

# === m17 ===
("m17-fsap-ibc-roster", "17", "FSAP + NIH OSP IBC roster ingestion",
 "Ingest the CDC/APHIS Federal Select Agent Program registered-entities list and the NIH OSP IBC registration roster. Pre-approve only entities present in these authoritative rosters for SOC orders.",
 "D", "no-ibc-approval, unauthorized-select-agent",
 "FSAP list; NIH OSP IBC list.",
 "fsap_not_listed; ibc_not_listed",
 "Reviewer reviews exceptions.",
 "Lists lag new registrations.",
 "Roster snapshot."),
("m17-igsc-shared-list", "17", "IGSC shared customer list + member CRM rollup",
 "International Gene Synthesis Consortium shared customer list — flag customers known to other IGSC members. Combine with internal CRM rollup of approval history.",
 "A", "industry-known-bad, cross-vendor-shopping",
 "IGSC shared list; internal CRM.",
 "igsc_flagged",
 "Reviewer reviews flagged customers.",
 "List freshness.",
 "IGSC record ID."),
("m17-positive-verification-sop", "17", "Annual positive-verification SOP",
 "Annual SOP that requires every pre-approved entity to be re-verified (institutional contact, IBC status, sanctions delta).",
 "D", "stale-pre-approval, post-approval-drift",
 "Internal SOP.",
 "annual_reverification_overdue",
 "Reviewer schedules re-verification.",
 "Manual workload.",
 "Re-verification log."),
("m17-event-driven-reeval", "17", "Event-driven re-eval (M&A, OFAC, breach, dormancy)",
 "Trigger re-evaluation of pre-approved entities on events: ownership change (OpenCorporates), OFAC delta (m01-delta), breach datasets (m16), prolonged dormancy.",
 "A", "post-approval-drift, m-and-a-laundering",
 "OpenCorporates events; m01 delta; SpyCloud; internal timers.",
 "event_triggered_reeval",
 "Reviewer adjudicates trigger.",
 "Event noise.",
 "Trigger record."),
("m17-predecessor-reidv", "17", "Predecessor pre-approval re-IAL2 + re-bind",
 "When an order arrives from a pre-approved entity, the submitting individual must complete re-IAL2 (m14) re-binding to the order. Closes inheritance of approval to new individuals.",
 "A", "predecessor-inheritance, dormant-account-takeover",
 "m14 IDV vendor.",
 "predecessor_rebind_failed",
 "Reviewer adjudicates legit handoffs.",
 "Friction.",
 "Re-bind record."),

# === m18 ===
("m18-ror", "18", "ROR Research Organization Registry",
 "Resolve the customer's claimed institution to a ROR ID. Check self-listing red flags (one-person-org-asserted-ROR, recent ROR creation, suspicious metadata). Foundational institution-identity signal used by many other ideas.",
 "D, A", "shell-nonprofit, foreign-institution, institution-impersonation",
 "ROR API.",
 "ror_no_match; ror_recent; ror_self_listed",
 "Reviewer adjudicates ambiguous matches.",
 "ROR coverage uneven outside US/EU.",
 "ROR ID + metadata."),
("m18-gleif", "18", "GLEIF LEI lookup + Level-2 relationships",
 "Resolve the institution to a Legal Entity Identifier via GLEIF. Capture Level-2 parent/ultimate-parent relationships to detect shell parents and beneficial-owner laundering.",
 "D, A", "shell-company, beneficial-owner-laundering",
 "GLEIF API.",
 "no_lei; lei_lapsed; lei_parent_in_concern_jurisdiction",
 "Reviewer reviews parent chains.",
 "LEI coverage skews to financial entities.",
 "LEI record + parent graph."),
("m18-companies-house-charity", "18", "UK CH + Charity Commission + US SOS + IRS TEOS",
 "National corporate / charity / nonprofit registries: UK Companies House + Charity Commission, US state SOS + IRS Tax Exempt Organization Search. Verify legal existence and status.",
 "D, A", "shell-company, dissolved-company, fake-nonprofit",
 "Companies House API; Charity Commission API; state SOS portals; IRS TEOS.",
 "registry_no_record; registry_dissolved",
 "Reviewer reviews edge cases.",
 "State SOS coverage uneven.",
 "Registry snapshot."),
("m18-nih-reporter", "18", "NIH RePORTER funded-institution signal",
 "Query NIH RePORTER for grants awarded to the institution in the past 5 years. Funded-institution status is strong positive evidence.",
 "A", "shell-nonprofit, paper-shell-research-org",
 "NIH RePORTER API.",
 "no_nih_funding_5yr",
 "Reviewer combines with other signals.",
 "Many legitimate non-NIH-funded labs.",
 "Grant count + sample IDs."),
("m18-nsf-awards", "18", "NSF + UKRI + ERC/CORDIS awards signal",
 "Same as m18-nih-reporter for non-medical funders: NSF Award Search, UKRI Gateway to Research, EU CORDIS / ERC. Captures grant history across major funders.",
 "A", "shell-nonprofit, paper-shell-research-org",
 "NSF Award Search; UKRI; CORDIS.",
 "no_funder_record_5yr",
 "Reviewer combines.",
 "Funder coverage uneven.",
 "Grant snapshots."),
("m18-accreditation-stack", "18", "Accreditation registry stack (CAP/CLIA/AAALAC/OLAW/ISO 17025/GLP/Global BioLabs)",
 "Cross-reference institution against domain-appropriate accreditation registries: CAP, CLIA/CMS QCOR, AAALAC, NIH OLAW, ISO 17025 (A2LA, ANAB, UKAS, DAkkS), GLP (OECD/FDA BIMO/MHRA), Global BioLabs map for high-containment.",
 "D, A", "fake-accreditation, paper-shell-research-org, fake-bsl",
 "CAP, CLIA, AAALAC, OLAW, A2LA/ANAB/UKAS, OECD GLP, Global BioLabs.",
 "claimed_accreditation_not_in_registry",
 "Reviewer compares claim to registries.",
 "Some registries gated; classified labs absent.",
 "Registry snapshot."),
("m18-cross-shell-graph", "18", "Cross-shell rotation graph",
 "Maintain a graph of every prior screened institution's registered agent, officer/director, WHOIS registrant, CT cert issuer/serial, NIH PI, and hosting fingerprint. Flag new customers sharing ≥2 fingerprints with prior entities.",
 "A", "cro-identity-rotation, shell-company, cro-framing",
 "Internal Neo4j/Postgres graph; Companies House officers; GLEIF L2; Censys/Shodan; crt.sh.",
 "cross_shell_shared_agent; cross_shell_shared_officer; cross_shell_shared_hosting; cross_shell_shared_pi",
 "Reviewer reviews linked-entity panel.",
 "Mass-formation agents; shared-PI false positives.",
 "Graph query result."),
("m18-lookalike-domain", "18", "Lookalike / homoglyph institutional-domain detector",
 "Detect homoglyph and typosquat variations of legitimate institutional domains via Punycode/UTS-39 confusables, Levenshtein ≤2 against ROR domains, dnstwist permutations, and CT first-seen age.",
 "A", "lookalike-domain, inbox-compromise, it-persona-manufacturing",
 "UTS #39; dnstwist; ROR domain corpus; crt.sh.",
 "domain_homoglyph_match; domain_levenshtein_le_2; domain_dnstwist_match",
 "Reviewer contacts real institution.",
 "Legitimate spinout domains adjacent to parent.",
 "Permutation report."),

# === m19 ===
("m19-orcid-employments", "19", "ORCID employment + education record",
 "Resolve the researcher to an ORCID ID; fetch employments and educations. Verify current employer matches claimed institution. Strong positive signal where ORCID is populated.",
 "D, A", "it-persona-manufacturing, gradual-legitimacy-accumulation, ghost-author",
 "ORCID public API.",
 "orcid_no_record; orcid_employer_mismatch; orcid_recent",
 "Reviewer adjudicates near-misses.",
 "ORCID self-asserted; coverage uneven.",
 "ORCID record."),
("m19-openalex-author", "19", "OpenAlex author + affiliation history",
 "Resolve the researcher to an OpenAlex author ID; fetch affiliation history, h-index, publication count, last_known_institution. Verify against claim.",
 "A", "ghost-author, it-persona-manufacturing, paper-shell-research-org",
 "OpenAlex API.",
 "openalex_no_author; openalex_affiliation_mismatch",
 "Reviewer adjudicates name disambiguation.",
 "Common-name disambiguation; OpenAlex authorship merging.",
 "Author record."),
("m19-pubmed-scopus", "19", "PubMed / Scopus author lookup",
 "Cross-source author verification via PubMed (NCBI E-utilities) and Scopus Author API. Used as a second source for OpenAlex.",
 "A", "ghost-author, it-persona-manufacturing",
 "NCBI E-utilities; Scopus API.",
 "no_pubmed_author; no_scopus_author",
 "Reviewer disambiguates.",
 "Scopus subscription required.",
 "Author IDs."),
("m19-nih-nsf-pi", "19", "NIH / NSF / Wellcome / ERC PI lookup",
 "Search NIH RePORTER, NSF Award Search, Wellcome Open Funder, ERC, and UKRI for grants where the customer is listed as PI or co-PI. PI status is strong positive evidence.",
 "A", "ghost-pi, it-persona-manufacturing",
 "NIH RePORTER; NSF; Wellcome; ERC; UKRI.",
 "no_pi_record; pi_at_different_institution",
 "Reviewer adjudicates name match.",
 "Most researchers are not PI.",
 "Grant records."),
("m19-clinicaltrials-investigator", "19", "ClinicalTrials.gov + FDA BIMO investigator",
 "Cross-check the researcher against ClinicalTrials.gov investigators and FDA BIMO clinical investigator inspections.",
 "A", "ghost-investigator",
 "ClinicalTrials.gov API; FDA BIMO database.",
 "no_ctgov_record; no_fda_bimo_record",
 "Reviewer reviews adjacent records.",
 "Many basic researchers absent.",
 "Investigator records."),
("m19-faculty-page", "19", "Faculty / lab page + institutional directory",
 "Fetch the researcher's faculty or lab page from the institution's website. Cross-check with the institutional directory (m07-directory-scrape).",
 "A", "it-persona-manufacturing, ghost-author",
 "Manual scrape; m07 directory.",
 "no_faculty_page; faculty_page_role_mismatch",
 "Reviewer reviews edge cases.",
 "Some institutions don't publish lab pages.",
 "Page snapshot."),
("m19-role-vs-scope", "19", "Role-vs-scope / seniority alignment SOP",
 "Reviewer SOP: the researcher's stated role and seniority must be plausible for the order's scope. A first-year grad student ordering BSL-3 select-agent reagents for an unaffiliated PI = escalate.",
 "A", "role-scope-mismatch, junior-as-front",
 "Manual.",
 "role_scope_implausible",
 "Reviewer documents reasoning.",
 "Subjective.",
 "SOP outcome."),

# === m20 ===
("m20-voucher-idv", "20", "Voucher IAL2 IDV",
 "Voucher must complete IAL2 IDV via m14 vendor (Jumio / Onfido / Persona). Voucher identity is bound to a verified document and biometric.",
 "D", "fake-voucher, synthetic-voucher",
 "m14 IDV stack.",
 "voucher_idv_failed",
 "Reviewer adjudicates failures.",
 "Voucher friction.",
 "IDV record."),
("m20-orcid-oauth", "20", "ORCID OAuth proof-of-control",
 "Voucher proves control of an ORCID ID via OAuth. Eliminates self-asserted ORCID claims.",
 "D", "fake-voucher, orcid-impersonation",
 "ORCID OAuth.",
 "orcid_oauth_failed",
 "Reviewer adjudicates ORCID-less voucher.",
 "Some legitimate vouchers lack ORCID.",
 "OAuth token."),
("m20-dkim-institutional-email", "20", "DKIM-verified institutional email from voucher",
 "Voucher must send their attestation from an institutional email; verify DKIM signature aligns with the institution's domain. Stops free-mail vouching.",
 "D, A", "fake-voucher, free-mail-voucher, lookalike-voucher-domain",
 "DKIM verifier; m02 ROR domain match.",
 "dkim_invalid; voucher_domain_not_institutional",
 "Reviewer adjudicates non-DKIM mail systems.",
 "Some institutions misconfigure DKIM.",
 "DKIM record."),
("m20-live-video-attestation", "20", "Live video attestation",
 "Voucher attests on a live video call holding their government ID. Hard for synthetic-identity factories to fake at scale.",
 "A", "fake-voucher, deepfake-voucher",
 "Manual scheduled call; recording.",
 "video_attestation_failed",
 "Reviewer conducts call.",
 "Time-intensive.",
 "Recording hash."),
("m20-coauthor-graph", "20", "OpenAlex coauthor / shared-grant independence graph",
 "Build a coauthor + shared-grant graph from OpenAlex + NIH/NSF; verify voucher and customer are genuinely independent (not coauthors, no shared grants in past 3 years). Detects collusive vouching.",
 "A", "collusive-vouching, ring-vouching",
 "OpenAlex; NIH RePORTER; NSF.",
 "voucher_customer_coauthors; voucher_customer_shared_grant",
 "Reviewer reviews edge cases.",
 "Legitimate collaborators.",
 "Graph distance."),
("m20-ror-disjointness", "20", "Voucher ↔ customer ROR disjointness",
 "Rule: voucher's ROR institution must be disjoint from the customer's ROR institution (or have a documented affiliation). Stops same-shell vouching.",
 "A", "shell-vouching, internal-vouching",
 "ROR; m18-ror.",
 "voucher_customer_same_ror",
 "Reviewer adjudicates legitimate same-institution cross-department vouching.",
 "Same-institution legitimate cases.",
 "ROR comparison."),
("m20-anti-rubber-stamp", "20", "Anti-rubber-stamp SOP",
 "Rate-limit the number of vouches a single voucher can issue per quarter; require diversity of customers; audit vouchers exceeding thresholds.",
 "A", "rubber-stamp-voucher, ring-vouching",
 "Internal limits.",
 "voucher_rate_exceeded; voucher_diversity_low",
 "Reviewer audits high-volume vouchers.",
 "Legitimate frequent vouchers (PIs).",
 "Voucher activity log."),
("m20-voucher-trust-score", "20", "Composite voucher trust score + institutional gate",
 "Composite score combining m20-voucher-idv, m20-orcid-oauth, m20-dkim-institutional-email, m19 seniority signals, and m18 institutional legitimacy. Hard gate at threshold.",
 "D, A", "fake-voucher, low-quality-voucher",
 "Internal scoring.",
 "voucher_trust_below_threshold",
 "Reviewer adjudicates borderline.",
 "Score opacity.",
 "Composite score."),
]

TEMPLATE = """# {slug}

- **measure:** M{measure}
- **name:** {name}
- **modes:** {modes}
- **summary:** {summary}
- **attacker_stories_addressed:** {stories}
- **external_dependencies:** {deps}
- **flags_thrown:** {flags}
- **manual_review_handoff:** {review}
- **failure_modes_requiring_review:** {failures}
- **record_left:** {record}
"""

def main():
    seen = set()
    for slug, measure, name, summary, modes, stories, deps, flags, review, failures, record in SPECS:
        if slug in seen:
            raise SystemExit(f"duplicate slug: {slug}")
        seen.add(slug)
        d = OUT / slug
        d.mkdir(parents=True, exist_ok=True)
        (d / "00-spec.md").write_text(TEMPLATE.format(
            slug=slug, measure=measure, name=name, summary=summary, modes=modes,
            stories=stories, deps=deps, flags=flags, review=review,
            failures=failures, record=record))
    print(f"wrote {len(SPECS)} specs")

if __name__ == "__main__":
    main()
